"""Domain models: SQLAlchemy ORM + Pydantic DTOs."""

from apps.backend.models.db import Base, get_session, init_db
from apps.backend.models.entities import (
    AnalyticsCriterion,
    AnalyticsCriteriaSet,
    Conversation,
    ConversationTurn,
    Document,
    Prompt,
    Voice,
)
from apps.backend.models.schemas import (
    AnalyticsCriteriaSetIn,
    AnalyticsCriteriaSetOut,
    AnalyticsCriterionIn,
    AnalyticsCriterionOut,
    CaseContext,
    ChatMessage,
    ConversationOut,
    ConversationTurnOut,
    CriterionScoreOut,
    DiarizedTurn,
    DocumentOut,
    EscalationPacket,
    IntentResult,
    PlaygroundRequest,
    PlaygroundResponse,
    PromptIn,
    PromptOut,
    RAGChunk,
    SpeechAnalysisResult,
    VoiceIn,
    VoiceOut,
    VoiceTtsPatch,
)

__all__ = [
    "Base",
    "get_session",
    "init_db",
    "AnalyticsCriterion",
    "AnalyticsCriteriaSet",
    "Conversation",
    "ConversationTurn",
    "Document",
    "Prompt",
    "Voice",
    "AnalyticsCriteriaSetIn",
    "AnalyticsCriteriaSetOut",
    "AnalyticsCriterionIn",
    "AnalyticsCriterionOut",
    "CaseContext",
    "ChatMessage",
    "ConversationOut",
    "ConversationTurnOut",
    "CriterionScoreOut",
    "DiarizedTurn",
    "DocumentOut",
    "EscalationPacket",
    "IntentResult",
    "PlaygroundRequest",
    "PlaygroundResponse",
    "PromptIn",
    "PromptOut",
    "RAGChunk",
    "SpeechAnalysisResult",
    "VoiceIn",
    "VoiceOut",
    "VoiceTtsPatch",
]
